name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Run Tests
      run: |
        python app/manage.py test

    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1  # Set up QEMU for building multi-platform images (optional)



    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        docker build -t sawangautam172/django:latest /app/Dockerfile .
        docker push sawangautam172/django:latest /app/Dockerfile

    # - name: Build and push Docker image
    #   run: |
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag django:$(date +%s)
      
    #     # # docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.DOCKERHUB_USERNAME }}"/django:latest .
    #     # # docker push sawangautam172@gmail.com/django:latest .
    #     # # Build the Docker image
    #     # docker build -t "${{ secrets.DOCKERHUB_USERNAME }}"/django:latest .

    #     # # Tag the Docker image (if not tagged during build)
    #     # docker sawan "${{ secrets.DOCKERHUB_USERNAME }}"/django:latest
        
    #     # # Push the Docker image to Docker Hub
    #     # docker push "${{ secrets.DOCKERHUB_USERNAME }}"/django:latest

      
